baseurl:
url: "http://hoamle.github.io" # the base hostname & protocol for your site
title: Hoa M. Le's Personal site
subtitle:
author: Hoa M. Le
simple_search: http://google.com/search
description:
name: tufte
markdown: Kramdown
kramdown:  
  input: GFM
  #syntax_highlighter: rouge
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: rouge
permalink: /articles/:short_year/:title
timezone: America/New_York
excerpt_separator: "" # <!--more-->  # you can specify your own separator, of course.
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: gvim
git:
  branch: source  # deploy source to `source`, locally published site to `master`
transfer:
  command: rsync
  settings: -av
  source: _site/
  destination: ~/Git/clayh53.github.com/
